### PR TITLE
fix: bad password

### LINKED ISSUE #155: Bad password crashes program
image

### PR DESCRIPTION
**Pull request by punctuations**
RELATED ISSUES:
- fixes #155

### CODE REVIEW

**Comment by tylerecouture** [comment]
@punctuations tests fail.

**Comment by punctuations** [comment]
This PR was made when the actions weren't setup properly, if it was to be rerun there shouldn't be any problems

**Comment by punctuations** [comment]
The action at that time had a bad image link which was solved with a different PR

**Comment by tylerecouture** [comment]
> The action at that time had a bad image link which was solved with a different PR

Ok, thanks. I'm rerunning the jobs

**Comment by tylerecouture** [comment]
@punctuations still failing.  Check the github actions test logs.  I assume you can see them?

**Comment by punctuations** [comment]
right! my bad, its because the actions on this PR are outdated, they were changed here: [timberline-secondary/hackerspace-scripts-2@`773d828` (#156)](https://github.com/timberline-secondary/hackerspace-scripts-2/pull/156/commits/773d828e5f80831639a14368b59310e428dbafca)

**Comment by tylerecouture** [comment]
Then can you merge and repush?

**Pull request closed without merging**
