### PR TITLE
fix: bad password

### LINKED ISSUE #155: Bad password crashes program
image

### PR DESCRIPTION
**Pull request by punctuations**
#### DESCRIPTION:
SSH connection was erroring out as the connection would not be established due to an incorrect password and then the program would call an undefined variable, thus causing the issue. This PR will add a check to ensure a connection is established successfully, else it will return gracefully

TECHNICAL CHANGES:
- Added statement to check if ssh_connection is established

RELATED ISSUES:
- Closes #155

### CODE REVIEW

**Comment by tylerecouture** [comment]
@punctuations It's failing.

**Comment by punctuations** [comment]
I forgot to add ffmpeg to the actions, can I add a commit to fix it here?

**Comment by tylerecouture** [comment]
Yep, then force push

**Comment by punctuations** [comment]
should be good now :+1:

**Pull request merged**
