### PR TITLE
fix: png transparency

### LINKED ISSUE #146: bad transparency mask error
When uploading this image:
https://d10ge8y4vx8iud.cloudfront.net/public_media/portfolios/video/2019/02/pikachu2.png

image

### PR DESCRIPTION
**Pull request by punctuations**
#### DESCRIPTION:
Fix png transparency, in this it will also now basically just remove alpha channel and keep whatever colour was supposed to be there (just without transparency)

TECHNICAL CHANGES:
- removed masking
- Changed to use PIL built-in `.convert('RGB')`

RELATED ISSUES:
- Fixes #146 (tested on a lab pc)

### CODE REVIEW

**Comment by tylerecouture** [comment]
How does it know what color was supposed to be there? What about fully transparent pixels?

**Comment by punctuations** [comment]
because the channels are broken up into rgba values like so:

rgba(255, 255, 255, 0)
This conversion essentially just removes alpha channel, transparent pixels will just be pixels that have an alpha value of 0, they will have a colour set by default so it will just have it has that

**Comment by tylerecouture** [comment]
I'm worried the backgrounds will go white (e.g. 255, 255, 255, 0), instead of black.

Can you test with some of our gifs and other transparent content? SVG, etc?

**Comment by tylerecouture** [comment]
Yes, if it's easy, that would prevent some unwanted surprises

**Comment by punctuations** [comment]
I made a change to go back to using the old way in that case, to just have a black background instead.

If I remember correct the actual problem wasn't removal of transparency but it just needed a black background so you didn't see the other images behind it?

If this was the issue this commit will fix as the only thing I changed from the original was checking to make sure both modes are the same (which is why the image in the issue was failing), the image in the original issue was a `.png` but without an alpha channel meaning it had its mode as `RGB`, whereas it was being pasted on an image (all back to act as a background) that has the mode of `RGBA`. < -- This issue has been fixed in the latest commit.

**Comment by tylerecouture** [comment]
Excellent.  Please test it with a transparent gif as well, to make sure that process wasn't broken

**Comment by punctuations** [comment]
I did, a fully transparent gif will just be all black

**Pull request merged**
